### ISSUE TITLE
MAPL/ESMF based interface for multi-grid WW3

### ISSUE THREAD

**Issue by adarmenov** [GEOS-ESM/WW3#1]
Use the NUOPC/ESMF module as a template to implement MAPL/ESMF based interface.

**Comment by adarmenov** [comment]
My changes/edits pertaining to this issue are in the branch feature/adarmenov/#1-mapl-iterface. The MAPL based interface module is in 'model/ftn/wmmaplmd.ftn'.

**Comment by atrayano** [comment]
I will take a look later today (after my 3-4 meeting)

**Comment by adarmenov** [comment]
I pushed the 'feature/adarmenov/#1-mapl-interface' branch. All of the changes that I made a month or so ago are committed at this point.

**Comment by atrayano** [comment]
Nice! Thanks
